language: node_js
node_js: stable

cache:
  directories:
    - node_modules

before_deploy:
  - "npm run doc:build"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master